# docker-compose.yml (dev)
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: poc_app
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - "3000:3000"
        volumes:
            - ./:/usr/src/app:delegated
            - app_node_modules:/usr/src/app/node_modules
        depends_on:
            - mongo
            - redis

    worker:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: poc_worker
        restart: unless-stopped
        env_file:
            - .env
        command: ["npm", "run", "worker:dev"]
        volumes:
            - ./:/usr/src/app:delegated
            - app_node_modules:/usr/src/app/node_modules
        depends_on:
            - mongo
            - redis

    mongo:
        image: mongo:6
        container_name: poc_mongo
        ports:
            - "27017:27017"
        volumes:
            - mongodata:/data/db

    redis:
        image: redis:7
        container_name: poc_redis
        ports:
            - "6379:6379"
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - redisdata:/data

    mongo-express:
        image: mongo-express:1.0.0
        container_name: poc_mongo_express
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: pass
        ports:
            - "8081:8081"
        depends_on:
            - mongo

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        container_name: poc_frontend
        environment:
            CHOKIDAR_USEPOLLING: "true"
            HOST: "0.0.0.0"
        ports:
            - "5173:5173"
        volumes:
            - ./frontend:/usr/src/app:delegated
            - frontend_node_modules:/usr/src/app/node_modules
        command: npm run dev -- --host 0.0.0.0 --port 5173
        depends_on:
            - app

volumes:
    app_node_modules:
    frontend_node_modules:
    mongodata:
    redisdata:
