version: "3.8"
services:
    mongo:
        image: mongo:6
        ports:
            - "27017:27017"
        volumes:
            - mongodata:/data/db

    redis:
        image: redis:7
        ports:
            - "6379:6379"
        command: ["redis-server", "--appendonly", "yes"]

volumes:
    mongodata:
